[package]
name = "bc"
version = "0.1.0"
authors = ["dwkim<dwkim@pentasecurity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
num-bigint = "0.2.3"
bytes = "0.5.2"
byteorder = "1.3.2"
